# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import soporte_pb2 as soporte__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in soporte_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SoporteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerarTicket = channel.unary_unary(
                '/soporte.SoporteService/GenerarTicket',
                request_serializer=soporte__pb2.NuevoTicketRequest.SerializeToString,
                response_deserializer=soporte__pb2.Ticket.FromString,
                _registered_method=True)
        self.AtenderSiguiente = channel.unary_unary(
                '/soporte.SoporteService/AtenderSiguiente',
                request_serializer=soporte__pb2.AtenderRequest.SerializeToString,
                response_deserializer=soporte__pb2.TicketAtendido.FromString,
                _registered_method=True)
        self.VerPendientes = channel.unary_unary(
                '/soporte.SoporteService/VerPendientes',
                request_serializer=soporte__pb2.Vacio.SerializeToString,
                response_deserializer=soporte__pb2.ResumenPendientes.FromString,
                _registered_method=True)


class SoporteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerarTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtenderSiguiente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerPendientes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoporteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerarTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerarTicket,
                    request_deserializer=soporte__pb2.NuevoTicketRequest.FromString,
                    response_serializer=soporte__pb2.Ticket.SerializeToString,
            ),
            'AtenderSiguiente': grpc.unary_unary_rpc_method_handler(
                    servicer.AtenderSiguiente,
                    request_deserializer=soporte__pb2.AtenderRequest.FromString,
                    response_serializer=soporte__pb2.TicketAtendido.SerializeToString,
            ),
            'VerPendientes': grpc.unary_unary_rpc_method_handler(
                    servicer.VerPendientes,
                    request_deserializer=soporte__pb2.Vacio.FromString,
                    response_serializer=soporte__pb2.ResumenPendientes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'soporte.SoporteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('soporte.SoporteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SoporteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerarTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soporte.SoporteService/GenerarTicket',
            soporte__pb2.NuevoTicketRequest.SerializeToString,
            soporte__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtenderSiguiente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soporte.SoporteService/AtenderSiguiente',
            soporte__pb2.AtenderRequest.SerializeToString,
            soporte__pb2.TicketAtendido.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerPendientes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/soporte.SoporteService/VerPendientes',
            soporte__pb2.Vacio.SerializeToString,
            soporte__pb2.ResumenPendientes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
