# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soporte.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'soporte.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsoporte.proto\x12\x07soporte\"M\n\x12NuevoTicketRequest\x12\x11\n\tprioridad\x18\x01 \x01(\t\x12\x0f\n\x07\x63liente\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\"Q\n\x06Ticket\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x11\n\tprioridad\x18\x02 \x01(\t\x12\x0f\n\x07\x63liente\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x04 \x01(\t\" \n\x0e\x41tenderRequest\x12\x0e\n\x06\x61gente\x18\x01 \x01(\t\"V\n\x0eTicketAtendido\x12\x12\n\nhay_ticket\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x1f\n\x06ticket\x18\x03 \x01(\x0b\x32\x0f.soporte.Ticket\">\n\x11ResumenPendientes\x12\x0c\n\x04\x61lta\x18\x01 \x01(\x05\x12\r\n\x05media\x18\x02 \x01(\x05\x12\x0c\n\x04\x62\x61ja\x18\x03 \x01(\x05\"\x07\n\x05Vacio2\xd2\x01\n\x0eSoporteService\x12=\n\rGenerarTicket\x12\x1b.soporte.NuevoTicketRequest\x1a\x0f.soporte.Ticket\x12\x44\n\x10\x41tenderSiguiente\x12\x17.soporte.AtenderRequest\x1a\x17.soporte.TicketAtendido\x12;\n\rVerPendientes\x12\x0e.soporte.Vacio\x1a\x1a.soporte.ResumenPendientesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soporte_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUEVOTICKETREQUEST']._serialized_start=26
  _globals['_NUEVOTICKETREQUEST']._serialized_end=103
  _globals['_TICKET']._serialized_start=105
  _globals['_TICKET']._serialized_end=186
  _globals['_ATENDERREQUEST']._serialized_start=188
  _globals['_ATENDERREQUEST']._serialized_end=220
  _globals['_TICKETATENDIDO']._serialized_start=222
  _globals['_TICKETATENDIDO']._serialized_end=308
  _globals['_RESUMENPENDIENTES']._serialized_start=310
  _globals['_RESUMENPENDIENTES']._serialized_end=372
  _globals['_VACIO']._serialized_start=374
  _globals['_VACIO']._serialized_end=381
  _globals['_SOPORTESERVICE']._serialized_start=384
  _globals['_SOPORTESERVICE']._serialized_end=594
# @@protoc_insertion_point(module_scope)
