# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import consultorio_pb2 as consultorio__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in consultorio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsultorioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerarTurno = channel.unary_unary(
                '/consultorio.ConsultorioService/GenerarTurno',
                request_serializer=consultorio__pb2.NuevoTurnoRequest.SerializeToString,
                response_deserializer=consultorio__pb2.Turno.FromString,
                _registered_method=True)
        self.AtenderSiguiente = channel.unary_unary(
                '/consultorio.ConsultorioService/AtenderSiguiente',
                request_serializer=consultorio__pb2.AtenderRequest.SerializeToString,
                response_deserializer=consultorio__pb2.TurnoAtendido.FromString,
                _registered_method=True)
        self.VerUltimos = channel.unary_stream(
                '/consultorio.ConsultorioService/VerUltimos',
                request_serializer=consultorio__pb2.Vacio.SerializeToString,
                response_deserializer=consultorio__pb2.UltimoLlamado.FromString,
                _registered_method=True)


class ConsultorioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerarTurno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtenderSiguiente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerUltimos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsultorioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerarTurno': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerarTurno,
                    request_deserializer=consultorio__pb2.NuevoTurnoRequest.FromString,
                    response_serializer=consultorio__pb2.Turno.SerializeToString,
            ),
            'AtenderSiguiente': grpc.unary_unary_rpc_method_handler(
                    servicer.AtenderSiguiente,
                    request_deserializer=consultorio__pb2.AtenderRequest.FromString,
                    response_serializer=consultorio__pb2.TurnoAtendido.SerializeToString,
            ),
            'VerUltimos': grpc.unary_stream_rpc_method_handler(
                    servicer.VerUltimos,
                    request_deserializer=consultorio__pb2.Vacio.FromString,
                    response_serializer=consultorio__pb2.UltimoLlamado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'consultorio.ConsultorioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('consultorio.ConsultorioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsultorioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerarTurno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consultorio.ConsultorioService/GenerarTurno',
            consultorio__pb2.NuevoTurnoRequest.SerializeToString,
            consultorio__pb2.Turno.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtenderSiguiente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consultorio.ConsultorioService/AtenderSiguiente',
            consultorio__pb2.AtenderRequest.SerializeToString,
            consultorio__pb2.TurnoAtendido.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerUltimos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/consultorio.ConsultorioService/VerUltimos',
            consultorio__pb2.Vacio.SerializeToString,
            consultorio__pb2.UltimoLlamado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
