# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import callcenter_pb2 as callcenter__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in callcenter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CallCenterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerarTicket = channel.unary_unary(
                '/callcenter.CallCenterService/GenerarTicket',
                request_serializer=callcenter__pb2.NuevoTicketRequest.SerializeToString,
                response_deserializer=callcenter__pb2.Ticket.FromString,
                _registered_method=True)
        self.AtenderPorIdioma = channel.unary_unary(
                '/callcenter.CallCenterService/AtenderPorIdioma',
                request_serializer=callcenter__pb2.AtenderIdiomaRequest.SerializeToString,
                response_deserializer=callcenter__pb2.TicketAtendido.FromString,
                _registered_method=True)
        self.VerEstadoIdiomas = channel.unary_stream(
                '/callcenter.CallCenterService/VerEstadoIdiomas',
                request_serializer=callcenter__pb2.Vacio.SerializeToString,
                response_deserializer=callcenter__pb2.EstadoIdioma.FromString,
                _registered_method=True)


class CallCenterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerarTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtenderPorIdioma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerEstadoIdiomas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallCenterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerarTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerarTicket,
                    request_deserializer=callcenter__pb2.NuevoTicketRequest.FromString,
                    response_serializer=callcenter__pb2.Ticket.SerializeToString,
            ),
            'AtenderPorIdioma': grpc.unary_unary_rpc_method_handler(
                    servicer.AtenderPorIdioma,
                    request_deserializer=callcenter__pb2.AtenderIdiomaRequest.FromString,
                    response_serializer=callcenter__pb2.TicketAtendido.SerializeToString,
            ),
            'VerEstadoIdiomas': grpc.unary_stream_rpc_method_handler(
                    servicer.VerEstadoIdiomas,
                    request_deserializer=callcenter__pb2.Vacio.FromString,
                    response_serializer=callcenter__pb2.EstadoIdioma.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'callcenter.CallCenterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('callcenter.CallCenterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CallCenterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerarTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callcenter.CallCenterService/GenerarTicket',
            callcenter__pb2.NuevoTicketRequest.SerializeToString,
            callcenter__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtenderPorIdioma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/callcenter.CallCenterService/AtenderPorIdioma',
            callcenter__pb2.AtenderIdiomaRequest.SerializeToString,
            callcenter__pb2.TicketAtendido.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerEstadoIdiomas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/callcenter.CallCenterService/VerEstadoIdiomas',
            callcenter__pb2.Vacio.SerializeToString,
            callcenter__pb2.EstadoIdioma.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
