# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: callcenter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'callcenter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61llcenter.proto\x12\ncallcenter\"5\n\x12NuevoTicketRequest\x12\x0e\n\x06idioma\x18\x01 \x01(\t\x12\x0f\n\x07\x63liente\x18\x02 \x01(\t\"9\n\x06Ticket\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0e\n\x06idioma\x18\x02 \x01(\t\x12\x0f\n\x07\x63liente\x18\x03 \x01(\t\"6\n\x14\x41tenderIdiomaRequest\x12\x0e\n\x06idioma\x18\x01 \x01(\t\x12\x0e\n\x06\x61gente\x18\x02 \x01(\t\"Y\n\x0eTicketAtendido\x12\x12\n\nhay_ticket\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\"\n\x06ticket\x18\x03 \x01(\x0b\x32\x12.callcenter.Ticket\"C\n\x0c\x45stadoIdioma\x12\x0e\n\x06idioma\x18\x01 \x01(\t\x12\x12\n\npendientes\x18\x02 \x01(\x05\x12\x0f\n\x07ultimos\x18\x03 \x03(\t\"\x07\n\x05Vacio2\xed\x01\n\x11\x43\x61llCenterService\x12\x43\n\rGenerarTicket\x12\x1e.callcenter.NuevoTicketRequest\x1a\x12.callcenter.Ticket\x12P\n\x10\x41tenderPorIdioma\x12 .callcenter.AtenderIdiomaRequest\x1a\x1a.callcenter.TicketAtendido\x12\x41\n\x10VerEstadoIdiomas\x12\x11.callcenter.Vacio\x1a\x18.callcenter.EstadoIdioma0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'callcenter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUEVOTICKETREQUEST']._serialized_start=32
  _globals['_NUEVOTICKETREQUEST']._serialized_end=85
  _globals['_TICKET']._serialized_start=87
  _globals['_TICKET']._serialized_end=144
  _globals['_ATENDERIDIOMAREQUEST']._serialized_start=146
  _globals['_ATENDERIDIOMAREQUEST']._serialized_end=200
  _globals['_TICKETATENDIDO']._serialized_start=202
  _globals['_TICKETATENDIDO']._serialized_end=291
  _globals['_ESTADOIDIOMA']._serialized_start=293
  _globals['_ESTADOIDIOMA']._serialized_end=360
  _globals['_VACIO']._serialized_start=362
  _globals['_VACIO']._serialized_end=369
  _globals['_CALLCENTERSERVICE']._serialized_start=372
  _globals['_CALLCENTERSERVICE']._serialized_end=609
# @@protoc_insertion_point(module_scope)
