# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\nbiblioteca\"\x15\n\x07LibroID\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x05Libro\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\r\n\x05\x61utor\x18\x03 \x01(\t\"\x07\n\x05Vacio\",\n\x0fResumenRegistro\x12\x19\n\x11total_registrados\x18\x01 \x01(\x05\">\n\x0bTransaccion\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x10\n\x08id_libro\x18\x02 \x01(\x05\x12\x0f\n\x07usuario\x18\x03 \x01(\t\"\x1f\n\x0c\x43onfirmacion\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2\x9c\x02\n\x11\x42ibliotecaService\x12\x38\n\x0e\x43onsultarLibro\x12\x13.biblioteca.LibroID\x1a\x11.biblioteca.Libro\x12\x36\n\x0cListarLibros\x12\x11.biblioteca.Vacio\x1a\x11.biblioteca.Libro0\x01\x12\x43\n\x0fRegistrarLibros\x12\x11.biblioteca.Libro\x1a\x1b.biblioteca.ResumenRegistro(\x01\x12P\n\x17TransaccionesTiempoReal\x12\x17.biblioteca.Transaccion\x1a\x18.biblioteca.Confirmacion(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIBROID']._serialized_start=29
  _globals['_LIBROID']._serialized_end=50
  _globals['_LIBRO']._serialized_start=52
  _globals['_LIBRO']._serialized_end=102
  _globals['_VACIO']._serialized_start=104
  _globals['_VACIO']._serialized_end=111
  _globals['_RESUMENREGISTRO']._serialized_start=113
  _globals['_RESUMENREGISTRO']._serialized_end=157
  _globals['_TRANSACCION']._serialized_start=159
  _globals['_TRANSACCION']._serialized_end=221
  _globals['_CONFIRMACION']._serialized_start=223
  _globals['_CONFIRMACION']._serialized_end=254
  _globals['_BIBLIOTECASERVICE']._serialized_start=257
  _globals['_BIBLIOTECASERVICE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
