# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: consultorio.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'consultorio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63onsultorio.proto\x12\x0b\x63onsultorio\";\n\x11NuevoTurnoRequest\x12\x14\n\x0c\x65specialidad\x18\x01 \x01(\t\x12\x10\n\x08paciente\x18\x02 \x01(\t\"?\n\x05Turno\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x14\n\x0c\x65specialidad\x18\x02 \x01(\t\x12\x10\n\x08paciente\x18\x03 \x01(\t\":\n\x0e\x41tenderRequest\x12\x14\n\x0c\x65specialidad\x18\x01 \x01(\t\x12\x12\n\nescritorio\x18\x02 \x01(\t\"V\n\rTurnoAtendido\x12\x11\n\thay_turno\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12!\n\x05turno\x18\x03 \x01(\x0b\x32\x12.consultorio.Turno\"\x07\n\x05Vacio\"6\n\rUltimoLlamado\x12\x14\n\x0c\x65specialidad\x18\x01 \x01(\t\x12\x0f\n\x07\x63odigos\x18\x02 \x03(\t2\xe5\x01\n\x12\x43onsultorioService\x12\x42\n\x0cGenerarTurno\x12\x1e.consultorio.NuevoTurnoRequest\x1a\x12.consultorio.Turno\x12K\n\x10\x41tenderSiguiente\x12\x1b.consultorio.AtenderRequest\x1a\x1a.consultorio.TurnoAtendido\x12>\n\nVerUltimos\x12\x12.consultorio.Vacio\x1a\x1a.consultorio.UltimoLlamado0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consultorio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUEVOTURNOREQUEST']._serialized_start=34
  _globals['_NUEVOTURNOREQUEST']._serialized_end=93
  _globals['_TURNO']._serialized_start=95
  _globals['_TURNO']._serialized_end=158
  _globals['_ATENDERREQUEST']._serialized_start=160
  _globals['_ATENDERREQUEST']._serialized_end=218
  _globals['_TURNOATENDIDO']._serialized_start=220
  _globals['_TURNOATENDIDO']._serialized_end=306
  _globals['_VACIO']._serialized_start=308
  _globals['_VACIO']._serialized_end=315
  _globals['_ULTIMOLLAMADO']._serialized_start=317
  _globals['_ULTIMOLLAMADO']._serialized_end=371
  _globals['_CONSULTORIOSERVICE']._serialized_start=374
  _globals['_CONSULTORIOSERVICE']._serialized_end=603
# @@protoc_insertion_point(module_scope)
