# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: saludo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'saludo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csaludo.proto\x12\x06saludo\"/\n\rSaludoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0e\n\x06idioma\x18\x02 \x01(\t\"\x1e\n\x0bSaludoReply\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2C\n\tSaludador\x12\x36\n\x08SayHello\x12\x15.saludo.SaludoRequest\x1a\x13.saludo.SaludoReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'saludo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALUDOREQUEST']._serialized_start=24
  _globals['_SALUDOREQUEST']._serialized_end=71
  _globals['_SALUDOREPLY']._serialized_start=73
  _globals['_SALUDOREPLY']._serialized_end=103
  _globals['_SALUDADOR']._serialized_start=105
  _globals['_SALUDADOR']._serialized_end=172
# @@protoc_insertion_point(module_scope)
