# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import saludo_pb2 as saludo__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in saludo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SaludadorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/saludo.Saludador/SayHello',
                request_serializer=saludo__pb2.SaludoRequest.SerializeToString,
                response_deserializer=saludo__pb2.SaludoReply.FromString,
                _registered_method=True)
        self.ObtenerHoraServidor = channel.unary_unary(
                '/saludo.Saludador/ObtenerHoraServidor',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=saludo__pb2.HoraServidorReply.FromString,
                _registered_method=True)
        self.SaludarLista = channel.unary_unary(
                '/saludo.Saludador/SaludarLista',
                request_serializer=saludo__pb2.SaludarListaRequest.SerializeToString,
                response_deserializer=saludo__pb2.SaludarListaReply.FromString,
                _registered_method=True)


class SaludadorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerHoraServidor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaludarLista(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaludadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=saludo__pb2.SaludoRequest.FromString,
                    response_serializer=saludo__pb2.SaludoReply.SerializeToString,
            ),
            'ObtenerHoraServidor': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerHoraServidor,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=saludo__pb2.HoraServidorReply.SerializeToString,
            ),
            'SaludarLista': grpc.unary_unary_rpc_method_handler(
                    servicer.SaludarLista,
                    request_deserializer=saludo__pb2.SaludarListaRequest.FromString,
                    response_serializer=saludo__pb2.SaludarListaReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'saludo.Saludador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('saludo.Saludador', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Saludador(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saludo.Saludador/SayHello',
            saludo__pb2.SaludoRequest.SerializeToString,
            saludo__pb2.SaludoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerHoraServidor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saludo.Saludador/ObtenerHoraServidor',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            saludo__pb2.HoraServidorReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaludarLista(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saludo.Saludador/SaludarLista',
            saludo__pb2.SaludarListaRequest.SerializeToString,
            saludo__pb2.SaludarListaReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
