# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import library_pb2 as library__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BibliotecaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarLibro = channel.unary_unary(
                '/biblioteca.BibliotecaService/ConsultarLibro',
                request_serializer=library__pb2.LibroID.SerializeToString,
                response_deserializer=library__pb2.Libro.FromString,
                _registered_method=True)
        self.ListarLibros = channel.unary_stream(
                '/biblioteca.BibliotecaService/ListarLibros',
                request_serializer=library__pb2.Vacio.SerializeToString,
                response_deserializer=library__pb2.Libro.FromString,
                _registered_method=True)
        self.RegistrarLibros = channel.stream_unary(
                '/biblioteca.BibliotecaService/RegistrarLibros',
                request_serializer=library__pb2.Libro.SerializeToString,
                response_deserializer=library__pb2.ResumenRegistro.FromString,
                _registered_method=True)
        self.TransaccionesTiempoReal = channel.stream_stream(
                '/biblioteca.BibliotecaService/TransaccionesTiempoReal',
                request_serializer=library__pb2.Transaccion.SerializeToString,
                response_deserializer=library__pb2.Confirmacion.FromString,
                _registered_method=True)


class BibliotecaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConsultarLibro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarLibros(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarLibros(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransaccionesTiempoReal(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BibliotecaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarLibro,
                    request_deserializer=library__pb2.LibroID.FromString,
                    response_serializer=library__pb2.Libro.SerializeToString,
            ),
            'ListarLibros': grpc.unary_stream_rpc_method_handler(
                    servicer.ListarLibros,
                    request_deserializer=library__pb2.Vacio.FromString,
                    response_serializer=library__pb2.Libro.SerializeToString,
            ),
            'RegistrarLibros': grpc.stream_unary_rpc_method_handler(
                    servicer.RegistrarLibros,
                    request_deserializer=library__pb2.Libro.FromString,
                    response_serializer=library__pb2.ResumenRegistro.SerializeToString,
            ),
            'TransaccionesTiempoReal': grpc.stream_stream_rpc_method_handler(
                    servicer.TransaccionesTiempoReal,
                    request_deserializer=library__pb2.Transaccion.FromString,
                    response_serializer=library__pb2.Confirmacion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biblioteca.BibliotecaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('biblioteca.BibliotecaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BibliotecaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/ConsultarLibro',
            library__pb2.LibroID.SerializeToString,
            library__pb2.Libro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarLibros(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/biblioteca.BibliotecaService/ListarLibros',
            library__pb2.Vacio.SerializeToString,
            library__pb2.Libro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarLibros(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/biblioteca.BibliotecaService/RegistrarLibros',
            library__pb2.Libro.SerializeToString,
            library__pb2.ResumenRegistro.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransaccionesTiempoReal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/biblioteca.BibliotecaService/TransaccionesTiempoReal',
            library__pb2.Transaccion.SerializeToString,
            library__pb2.Confirmacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
